// Mocks generated by Mockito 5.4.0 from annotations
// in minh_interview_project/test/bloc_test/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:minh_interview_project/domain/entities/vehicle_entity.dart'
    as _i4;
import 'package:minh_interview_project/domain/reporisoty/repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Repository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i2.Repository {
  @override
  _i3.Future<List<_i4.VehicleEntity>> getListVehicle(
          {required int? startFrom}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListVehicle,
          [],
          {#startFrom: startFrom},
        ),
        returnValue:
            _i3.Future<List<_i4.VehicleEntity>>.value(<_i4.VehicleEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.VehicleEntity>>.value(<_i4.VehicleEntity>[]),
      ) as _i3.Future<List<_i4.VehicleEntity>>);
}
